# -*- coding: utf-8 -*-
"""granite-vision-3.2-2b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//huggingface.co/ibm-granite/granite-vision-3.2-2b.ipynb
"""



"""## Local Inference on GPU
Model page: https://huggingface.co/ibm-granite/granite-vision-3.2-2b

⚠️ If the generated code snippets do not work, please open an issue on either the [model repo](https://huggingface.co/ibm-granite/granite-vision-3.2-2b)
			and/or on [huggingface.js](https://github.com/huggingface/huggingface.js/blob/main/packages/tasks/src/model-libraries-snippets.ts) 🙏
"""

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("image-text-to-text", model="ibm-granite/granite-vision-3.2-2b")
messages = [
    {
        "role": "user",
        "content": [
            {"type": "image", "url": "https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/p-blog/candy.JPG"},
            {"type": "text", "text": "What animal is on the candy?"}
        ]
    },
]
pipe(text=messages)

# Load model directly
from transformers import AutoProcessor, AutoModelForImageTextToText

processor = AutoProcessor.from_pretrained("ibm-granite/granite-vision-3.2-2b")
model = AutoModelForImageTextToText.from_pretrained("ibm-granite/granite-vision-3.2-2b")
messages = [
    {
        "role": "user",
        "content": [
            {"type": "image", "url": "https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/p-blog/candy.JPG"},
            {"type": "text", "text": "What animal is on the candy?"}
        ]
    },
]
inputs = processor.apply_chat_template(
	messages,
	add_generation_prompt=True,
	tokenize=True,
	return_dict=True,
	return_tensors="pt",
).to(model.device)

outputs = model.generate(**inputs, max_new_tokens=40)
print(processor.decode(outputs[0][inputs["input_ids"].shape[-1]:]))

!pip install -q gradio

import gradio as gr
import re
import random
from datetime import datetime

"""COLOR PALETTES"""

palettes = {
    "Modern": ["#2563EB", "#1E293B", "#F8FAFC", "#38BDF8"],
    "Vibrant": ["#F43F5E", "#F59E0B", "#10B981", "#3B82F6"],
    "Ocean": ["#0EA5E9", "#0284C7", "#E0F2FE", "#075985"],
    "Forest": ["#166534", "#22C55E", "#ECFDF5", "#14532D"],
    "Sunset": ["#F97316", "#FB923C", "#FEF3C7", "#7C2D12"],
    "Luxury": ["#111827", "#D4AF37", "#F9FAFB", "#374151"],
    "Creative": ["#9333EA", "#F472B6", "#FDE68A", "#4F46E5"],
    "Minimal": ["#18181B", "#71717A", "#FAFAFA", "#A1A1AA"]
}

"""SECTION DETECTION"""

def detect_sections(text):
    text = text.lower()

    sections = []

    if "hero" in text or "landing" in text:
        sections.append("hero")

    if "portfolio" in text or "gallery" in text:
        sections.append("portfolio")

    if "about" in text:
        sections.append("about")

    if "service" in text or "feature" in text:
        sections.append("services")

    if "testimonial" in text:
        sections.append("testimonials")

    if "team" in text:
        sections.append("team")

    if "pricing" in text:
        sections.append("pricing")

    if "contact" in text:
        sections.append("contact")

    if not sections:
        sections = ["hero", "about", "services","testimonials","team","pricing", "contact"]

    return sections

"""HTML SECTION GENERATORS"""

def hero_section(title):
    return f"""
<section class='hero'>
<h1>{title}</h1>
<p>Welcome to our modern website created with HTML Quick Styler.</p>
<button>Get Started</button>
</section>
"""


def about_section():
    return """
<section class='about'>
<h2>About Us</h2>
<p>We create modern web experiences with responsive design and elegant UI.</p>
</section>
"""


def services_section():
    return """
<section class='services'>
<h2>Our Services</h2>
<div class='grid'>
<div class='card'>Web Design</div>
<div class='card'>UI/UX</div>
<div class='card'>Development</div>
</div>
</section>
"""


def portfolio_section():
    return """
<section class='portfolio'>
<h2>Portfolio</h2>
<div class='grid'>
<div class='card'>Project 1</div>
<div class='card'>Project 2</div>
<div class='card'>Project 3</div>
</div>
</section>
"""


def testimonial_section():
    return """
<section class='testimonials'>
<h2>Testimonials</h2>
<p>"Amazing service and great design!"</p>
</section>
"""


def team_section():
    return """
<section class='team'>
<h2>Our Team</h2>
<div class='grid'>
<div class='card'>Member 1</div>
<div class='card'>Member 2</div>
<div class='card'>Member 3</div>
</div>
</section>
"""


def pricing_section():
    return """
<section class='pricing'>
<h2>Pricing</h2>
<div class='grid'>
<div class='card'>Basic Plan</div>
<div class='card'>Pro Plan</div>
<div class='card'>Enterprise</div>
</div>
</section>
"""


def contact_section():
    return """
<section class='contact'>
<h2>Contact Us</h2>
<form>
<input placeholder='Name'>
<input placeholder='Email'>
<textarea placeholder='Message'></textarea>
<button>Send</button>
</form>
</section>
"""
def build_page(title):

    html = f"""
<html>
<head>
<title>{title}</title>
</head>
<body>
<h1>{title}</h1>
</body>
</html>
"""
    return html  
    
def generate_website(description, palette):

    title = "My Generated Website"

    html = build_page(title)

    return html
   

"""CSS GENERATOR"""

def generate_css(colors):

    primary, dark, light, accent = colors

    return f"""
body {{
font-family: Arial, sans-serif;
margin:0;
background:{light};
color:{dark};
}}

section {{
padding:60px;
text-align:center;
}}

.hero {{
background:{primary};
color:white;
padding:100px 20px;
}}

button {{
background:{accent};
border:none;
padding:12px 25px;
color:white;
cursor:pointer;
border-radius:6px;
}}

.grid {{
display:grid;
grid-template-columns:repeat(auto-fit,minmax(200px,1fr));
gap:20px;
margin-top:20px;
}}

.card {{
background:white;
padding:20px;
border-radius:10px;
box-shadow:0 4px 10px rgba(0,0,0,0.1);
}}

footer {{
background:{dark};
color:white;
text-align:center;
padding:20px;
}}
"""

"""MAIN GENERATOR"""

def generate_page(title, description, palette):

    sections = detect_sections(description)

    colors = palettes[palette]

    html_sections = ""

    for sec in sections:

        if sec == "hero":
            html_sections += hero_section(title)

        if sec == "about":
            html_sections += about_section()

        if sec == "services":
            html_sections += services_section()

        if sec == "portfolio":
            html_sections += portfolio_section()

        if sec == "testimonials":
            html_sections += testimonial_section()

        if sec == "team":
            html_sections += team_section()

        if sec == "pricing":
            html_sections += pricing_section()

        if sec == "contact":
            html_sections += contact_section()

    css = generate_css(colors)

    html = f"""
<!DOCTYPE html>
<html>
<head>
<title>{title}</title>
<style>
{css}
</style>
</head>

<body>

{html_sections}

<footer>
<p>Generated by HTML Quick Styler | {datetime.now().year}</p>
</footer>

</body>
</html>
"""

    return html

"""GRADIO INTERFACE"""

import gradio as gr

with gr.Blocks() as demo:

    gr.Markdown("# 🚀 HTML Quick-Styler")

    title = gr.Textbox(label="Website Title")

    description = gr.Textbox(
        label="Describe your website (portfolio, hero, pricing, team, etc.)",
        lines=4
    )

    palette = gr.Dropdown(
        choices=list(palettes.keys()),
        value="Modern",
        label="Choose Color Palette"
    )

    generate_btn = gr.Button("Generate Website")

    output = gr.Code(language="html")

    generate_btn.click(
        fn=generate_page,
        inputs=[title, description, palette],
        outputs=output
    )

demo.launch(share=True)